### PR TITLE
Set up LD_LIBRARY_PATH and PATH to include the pdftk binaries

### PR DESCRIPTION
**Pull request by sguha00**

### CODE REVIEW

**Comment by AdamBrodzinski** [comment]
@fxtentacle I can confirm this PR works. Thanks @sguha00 !! 🍻

**Comment by willemmulder** [comment]
@fxtentacle Can this be merged? That would really help us :-)

**Comment by dopeboy** [comment]
This worked out of the box for me too. Thanks @sguha00

**Comment by fxtentacle** [comment]
fixed by PR #5

**Pull request closed without merging**
