### PR TITLE
Add heroku 18 binaries

### LINKED ISSUE #8: support heroku-18 stack
Can you help me understand what it would take to add support for the new heroku-18 stack? I'm a newbie when it comes to making Heroku buildpacks, but if you point me in the right direction I'd be happy to help make it happen.

I forked and attempted it myself by just copying the `binaries-heroku-16`, to one named `binaries-heroku-18` but that didn't seem to do the trick.

https://github.com/kylekeesling/heroku-pdftk-buildpack

### PR DESCRIPTION
**Pull request by Aesthetikx**
I have added pdftk binaries that seem to be working for me on the heroku 18 stack. (Closes #8).

The process I used to obtain the binaries was basically adding the ubuntu artful sources to a heroku:heroku-18 docker container, then installing libgcj-common, libgcj17, and pdftk as explained [here](https://askubuntu.com/questions/1029450/how-to-install-pdftk-on-ubuntu-18-04-bionic/1035435). This is because for whatever reason those packages are not available on bionic yet. Regardless, the pdftk binary runs on the docker container and is also able to generate filled pdfs in a heroku environment running stack 18, although I have not tested it extensively beyond that.

### CODE REVIEW

**Comment by jacquescrocker** [comment]
I tested Aesthetikx's branch and it works well for me.

**Comment by coorasse** [comment]
I tested it and is working well for me too

**Comment by c990802** [comment]
@Aesthetikx Would be great if you could merge this branch :)

**Comment by imayolas** [comment]
@fxtentacle Could you merge this PR? Works like a charm. thanks :)

**Comment by jay-meister** [comment]
Works well, thanks all 👍

**Comment by fxtentacle** [comment]
Due to my particular deployment situation, this pdftk binary didn't work. I have now updated the build script and added binaries that were compiled natively on a heroku-18 dyno.

**Pull request closed without merging**
